# Generated by Django 3.2.6 on 2021-08-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dataset_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataset',
            name='short_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataset',
            name='tsne_bar_image',
            field=models.ImageField(default=None, upload_to='tsne_bar/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='tsne_full',
            field=models.ImageField(default=None, upload_to='tsne_full/'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='card_image',
            field=models.ImageField(default=None, upload_to='cards/'),
        ),
    ]
