# Generated by Django 3.2.6 on 2021-08-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210824_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='card_image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='tsne_bar_image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='tsne_full',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
