# Generated by Django 3.2.6 on 2021-08-26 16:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dataset_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='card_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='tsne_bar_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='tsne_full',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
